# Generated by Django 4.2.1 on 2024-02-19 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('1', 'Local'), ('2', 'Outstation'), ('3', 'Drop')], max_length=10)),
                ('date_of_enquiry', models.DateTimeField(default=datetime.datetime.now)),
                ('client_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=20)),
                ('duty_hours', models.CharField(choices=[('1', '4 Hours'), ('2', '8 Hours'), ('3', '12 Hours')], max_length=10)),
                ('car_details', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_management.adddriver')),
            ],
        ),
        migrations.CreateModel(
            name='driverenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('required_service', models.CharField(blank=True, max_length=200, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('enq_updated_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('enq_created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('enq_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
