# Generated by Django 4.2.1 on 2023-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebooking',
            name='packege',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
