# Generated by Django 4.2.1 on 2023-09-02 06:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebooking',
            name='currant_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT (0 0)', null=True, srid=4326),
        ),
    ]
