# Generated by Django 4.2.1 on 2023-09-15 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_placebooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(blank=True, choices=[('accept', 'accept'), ('decline', 'decline'), ('pending', 'pending'), ('completed', 'completed')], max_length=50, null=True)),
                ('booking_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.placebooking')),
                ('drivername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
