# Generated by Django 4.2.1 on 2023-09-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="adddriver", name="end_doh_date",),
    ]
