# Generated by Django 4.2.1 on 2023-09-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_master", "0001_initial"),
        ("driver_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_upload", models.ImageField(default=None, upload_to="media")),
                ("first_name", models.CharField(default=None, max_length=20)),
                ("middle_name", models.CharField(blank=True, max_length=20, null=True)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, default="Male", max_length=20, null=True
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("mobile", models.CharField(max_length=15)),
                ("alt_mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("religion", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "qualification",
                    models.CharField(
                        blank=True, default="SS", max_length=20, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, default="Hindi", max_length=100, null=True
                    ),
                ),
                ("temp_address", models.CharField(max_length=200)),
                ("permanent_address", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("aggrement_expiry_date", models.DateField(blank=True, null=True)),
                ("licence_no", models.CharField(max_length=20)),
                ("licence_issued_from", models.CharField(max_length=20)),
                (
                    "licence_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_of_issue", models.DateField()),
                ("date_of_expiry", models.DateField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.city",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.state",
                    ),
                ),
            ],
        ),
    ]
