# Generated by Django 4.2.1 on 2023-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddriver',
            name='end_doh_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='police_verification',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Certified', 'Certified'), ('Rejected', 'Rejected')], max_length=10),
        ),
    ]
