# Generated by Django 4.2.1 on 2023-09-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverlocation",
            name="driver_details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="driver_management.adddriver",
            ),
            preserve_default=False,
        ),
    ]
