# Generated by Django 4.2.1 on 2023-09-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_master", "0001_initial"),
        ("driver_management", "0002_remove_adddriver_end_doh_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_upload", models.ImageField(default=None, upload_to="media")),
                ("first_name", models.CharField(default=None, max_length=20)),
                ("middle_name", models.CharField(blank=True, max_length=20, null=True)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("mobile", models.CharField(max_length=15)),
                ("alt_mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "email",
                    models.EmailField(default="info@driveronhire.com", max_length=254),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("Married", "Married"), ("Single", "Single")],
                        max_length=10,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("Hindu", "Hindu"),
                            ("Muslim", "Muslim"),
                            ("Christian", "Christian"),
                            ("Sikh", "Sikh"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("5", "5th"),
                            ("6", "6th"),
                            ("7", "7th"),
                            ("8", "8th"),
                            ("9", "9th"),
                            ("SSC", "SSC"),
                            ("HSC", "HSC"),
                            ("BC", "BCOM"),
                            ("BS", "BSc"),
                            ("BE", "BE"),
                            ("BA", "BA"),
                        ],
                        default="SS",
                        max_length=10,
                    ),
                ),
                (
                    "driver_type",
                    models.CharField(
                        choices=[
                            ("Part Time", "Part Time"),
                            ("Full Time", "Full Time"),
                        ],
                        default="Temporary",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Hindi", "Hindi"),
                            ("English", "English"),
                            ("Bhojpuri", "Bhojpuri"),
                        ],
                        default="Hindi",
                        max_length=100,
                    ),
                ),
                ("t_address", models.CharField(max_length=200)),
                ("p_address", models.CharField(max_length=200)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("aggrement_expiry_date", models.DateField()),
                ("licence_no", models.CharField(max_length=20)),
                ("licence_issued_from", models.CharField(max_length=20)),
                (
                    "licence_type",
                    models.CharField(
                        choices=[("LMV-TR", "LMV-TR"), ("LMV-NT", "LMV-NT")],
                        default="TR",
                        max_length=10,
                    ),
                ),
                ("date_of_issue", models.DateField()),
                ("date_of_expiry", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.branch",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.city",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.location",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.state",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_master.zone",
                    ),
                ),
            ],
        ),
    ]
