# Generated by Django 4.2.1 on 2023-09-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0002_basicdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicDetails',
        ),
    ]
