# Generated by Django 4.2.1 on 2023-09-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0002_driverlocation_driver_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlocation",
            name="driver_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="driver_management.adddriver",
            ),
        ),
    ]
