# Generated by Django 4.2.1 on 2023-09-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0003_basicdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="aggrement_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
