# Generated by Django 4.2.1 on 2023-09-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0003_alter_driverlocation_driver_details"),
    ]

    operations = [
        migrations.RemoveField(model_name="driverlocation", name="driver_details",),
    ]
