# Generated by Django 4.2.1 on 2023-09-18 06:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0004_remove_driverlocation_driver_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="adddriver",
            name="driverlocation",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Point(longitude latitude)",
                null=True,
                srid=4326,
                verbose_name="Location in Map",
            ),
        ),
    ]
