# Generated by Django 4.2.1 on 2023-09-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0004_alter_basicdetails_aggrement_expiry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="basicdetails", name="branch",),
        migrations.RemoveField(model_name="basicdetails", name="driver_type",),
        migrations.RemoveField(model_name="basicdetails", name="zone",),
    ]
