# Generated by Django 4.2.1 on 2023-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0005_remove_basicdetails_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="language",
            field=models.CharField(
                choices=[
                    ("Hindi", "Hindi"),
                    ("English", "English"),
                    ("Marathi", "Marathi"),
                    ("Bhojpuri", "Bhojpuri"),
                ],
                default="Hindi",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="basicdetails",
            name="qualification",
            field=models.CharField(
                choices=[
                    ("SSC", "SSC"),
                    ("HSC", "HSC"),
                    ("Below SSC", "Below SSC"),
                    ("Below HSC", "Below HSC"),
                    ("Graduate", "Graduate"),
                ],
                default="SS",
                max_length=10,
            ),
        ),
    ]
