# Generated by Django 4.2.1 on 2023-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0005_adddriver_driverlocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adddriver",
            name="driver_type",
            field=models.CharField(
                choices=[("Part Time", "Part Time"), ("Full Time", "Full Time")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="adddriver",
            name="transmission_type",
            field=models.CharField(
                choices=[
                    ("Manual", "Manual"),
                    ("Automatic", "Automatic"),
                    ("Luxury", "Luxury"),
                    ("All", "All"),
                ],
                max_length=10,
            ),
        ),
    ]
