# Generated by Django 4.2.1 on 2023-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0006_alter_basicdetails_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicdetails",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
