# Generated by Django 4.2.1 on 2023-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_management", "0007_driverleave_driver_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverleave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
