# Generated by Django 4.2.1 on 2023-09-25 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_management', '0008_driverleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referdriver',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_master.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referdriver',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referdriver',
            name='mobile',
            field=models.PositiveBigIntegerField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referdriver',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referdriver',
            name='referdrivername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
