# Generated by Django 4.2.1 on 2023-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0009_referdriver_branch_referdriver_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referdriver',
            name='referdrivername',
        ),
        migrations.AlterField(
            model_name='referdriver',
            name='mobile',
            field=models.PositiveBigIntegerField(),
        ),
    ]
