# Generated by Django 4.2.1 on 2023-09-26 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_management', '0010_remove_referdriver_referdrivername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referdriver',
            name='referdrivername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
